# Shell variables
# Generated by 'wal'
wallpaper='/home/fw/pictures/wallpapers/sundown-over-sea.jpg'

# Special
background='#0A0B0F'
foreground='#e1cdbf'
cursor='#e1cdbf'

# Colors
color0='#0A0B0F'
color1='#30575F'
color2='#5A595A'
color3='#A56039'
color4='#BD8D6D'
color5='#407E81'
color6='#549596'
color7='#e1cdbf'
color8='#9d8f85'
color9='#30575F'
color10='#5A595A'
color11='#A56039'
color12='#BD8D6D'
color13='#407E81'
color14='#549596'
color15='#e1cdbf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
